FROM registry.access.redhat.com/rhscl/mysql-57-rhel7:latest

ENV MYSQL_USER="user" \
    MYSQL_PASSWORD="password" \
    MYSQL_ROOT_PASSWORD="password" \
    MYSQL_DATABASE="socksdb"

COPY db /opt/app-root/src 
